<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Navislamia.Game</RootNamespace>
    <Platforms>x64</Platforms>
    <AssemblyName>Modules.Game</AssemblyName>
    <LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripting/Scripts/event_area_functions.json" LogicalName="Navislamia.EventAreaFunctions.json" />
    <EmbeddedResource Include="DataAccess/Migrations/Arcadia/EventAreaResources.sql" LogicalName="Navislamia.EventAreaResources.sql" />
    <EmbeddedResource Include="Scripting/Scripts/npc_dialogs.json" LogicalName="Navislamia.NpcDialogs.json" />
    <EmbeddedResource Include="Scripting/Scripts/guild_dialogs.json" LogicalName="Navislamia.GuildDialogs.json" />
    <EmbeddedResource Include="Services/Dungeons/dungeon-resources.json" LogicalName="Navislamia.DungeonResources.json" />
    <ProjectReference Include="..\Configuration\Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripting/Scripts/monster_triggers.lua" LogicalName="Navislamia.MonsterTriggers.lua" />
    <EmbeddedResource Include="Scripting/Scripts/monster_trigger_profiles.lua" LogicalName="Navislamia.MonsterTriggerProfiles.lua" />
    <EmbeddedResource Include="Services/Progression/progression-resources.json" LogicalName="Navislamia.ProgressionResources.json" />
    <EmbeddedResource Include="DataAccess/Migrations/Arcadia/ItemWearRestrictions.sql" LogicalName="Navislamia.ItemWearRestrictions.sql" />
  </ItemGroup>
</Project>
