using Microsoft.EntityFrameworkCore;

namespace MigrateDatabase.MssqlEntities.Arcadia;

[PrimaryKey(nameof(id))]
public class MSSQLMixResource
{
    public int id { get; set; }
    public int mix_type { get; set; }
    public int mix_value_01 { get; set; }
    public int mix_value_02 { get; set; }
    public int mix_value_03 { get; set; }
    public int mix_value_04 { get; set; }
    public int mix_value_05 { get; set; }
    public int mix_value_06 { get; set; }
    public int sub_material_count { get; set; }
    public int main_type_01 { get; set; }
    public int main_value_01 { get; set; }
    public int main_type_02 { get; set; }
    public int main_value_02 { get; set; }
    public int main_type_03 { get; set; }
    public int main_value_03 { get; set; }
    public int main_type_04 { get; set; }
    public int main_value_04 { get; set; }
    public int main_type_05 { get; set; }
    public int main_value_05 { get; set; }
    public int sub01_type_01 { get; set; }
    public int sub01_value_01 { get; set; }
    public int sub01_type_02 { get; set; }
    public int sub01_value_02 { get; set; }
    public int sub01_type_03 { get; set; }
    public int sub01_value_03 { get; set; }
    public int sub01_type_04 { get; set; }
    public int sub01_value_04 { get; set; }
    public int sub01_type_05 { get; set; }
    public int sub01_value_05 { get; set; }
    public int sub02_type_01 { get; set; }
    public int sub02_value_01 { get; set; }
    public int sub02_type_02 { get; set; }
    public int sub02_value_02 { get; set; }
    public int sub02_type_03 { get; set; }
    public int sub02_value_03 { get; set; }
    public int sub02_type_04 { get; set; }
    public int sub02_value_04 { get; set; }
    public int sub02_type_05 { get; set; }
    public int sub02_value_05 { get; set; }
    public int sub03_type_01 { get; set; }
    public int sub03_value_01 { get; set; }
    public int sub03_type_02 { get; set; }
    public int sub03_value_02 { get; set; }
    public int sub03_type_03 { get; set; }
    public int sub03_value_03 { get; set; }
    public int sub03_type_04 { get; set; }
    public int sub03_value_04 { get; set; }
    public int sub03_type_05 { get; set; }
    public int sub03_value_05 { get; set; }
    public int sub04_type_01 { get; set; }
    public int sub04_value_01 { get; set; }
    public int sub04_type_02 { get; set; }
    public int sub04_value_02 { get; set; }
    public int sub04_type_03 { get; set; }
    public int sub04_value_03 { get; set; }
    public int sub04_type_04 { get; set; }
    public int sub04_value_04 { get; set; }
    public int sub04_type_05 { get; set; }
    public int sub04_value_05 { get; set; }
    public int sub05_type_01 { get; set; }
    public int sub05_value_01 { get; set; }
    public int sub05_type_02 { get; set; }
    public int sub05_value_02 { get; set; }
    public int sub05_type_03 { get; set; }
    public int sub05_value_03 { get; set; }
    public int sub05_type_04 { get; set; }
    public int sub05_value_04 { get; set; }
    public int sub05_type_05 { get; set; }
    public int sub05_value_05 { get; set; }
    public int sub06_type_01 { get; set; }
    public int sub06_value_01 { get; set; }
    public int sub06_type_02 { get; set; }
    public int sub06_value_02 { get; set; }
    public int sub06_type_03 { get; set; }
    public int sub06_value_03 { get; set; }
    public int sub06_type_04 { get; set; }
    public int sub06_value_04 { get; set; }
    public int sub06_type_05 { get; set; }
    public int sub06_value_05 { get; set; }
    public int sub07_type_01 { get; set; }
    public int sub07_value_01 { get; set; }
    public int sub07_type_02 { get; set; }
    public int sub07_value_02 { get; set; }
    public int sub07_type_03 { get; set; }
    public int sub07_value_03 { get; set; }
    public int sub07_type_04 { get; set; }
    public int sub07_value_04 { get; set; }
    public int sub07_type_05 { get; set; }
    public int sub07_value_05 { get; set; }
    public int sub08_type_01 { get; set; }
    public int sub08_value_01 { get; set; }
    public int sub08_type_02 { get; set; }
    public int sub08_value_02 { get; set; }
    public int sub08_type_03 { get; set; }
    public int sub08_value_03 { get; set; }
    public int sub08_type_04 { get; set; }
    public int sub08_value_04 { get; set; }
    public int sub08_type_05 { get; set; }
    public int sub08_value_05 { get; set; }
    public int sub09_type_01 { get; set; }
    public int sub09_value_01 { get; set; }
    public int sub09_type_02 { get; set; }
    public int sub09_value_02 { get; set; }
    public int sub09_type_03 { get; set; }
    public int sub09_value_03 { get; set; }
    public int sub09_type_04 { get; set; }
    public int sub09_value_04 { get; set; }
    public int sub09_type_05 { get; set; }
    public int sub09_value_05 { get; set; }
}
