namespace Navislamia.Game.DataAccess.Entities.Arcadia;

public class MonsterResourceEntity : Entity
{
    public int MonsterGroup { get; set; }
    public int NameId { get; set; }
    public int LocationId { get; set; }
    public string Model { get; set; }
    public int MotionFileId { get; set; }
    public int TransformLevel { get; set; }
    public int WalkType { get; set; }
    public int SlantType { get; set; }
    public decimal Size { get; set; }
    public decimal Scale { get; set; }
    public decimal TargetFxSize { get; set; }
    public int CameraX { get; set; }
    public int CameraY { get; set; }
    public int CameraZ { get; set; }
    public decimal TargetX { get; set; }
    public decimal TargetY { get; set; }
    public decimal TargetZ { get; set; }
    public int Level { get; set; }
    public int Grp { get; set; }
    public int Affiliation { get; set; }
    public int SpeciesId { get; set; }
    public int MagicType { get; set; }
    public int Race { get; set; }
    public int VisibleRange { get; set; }
    public int ChaseRange { get; set; }
    public int FirstAttack { get; set; }
    public int GroupFirstAttack { get; set; }
    public int ResponseCasting { get; set; }
    public int ResponseRace { get; set; }
    public int ResponseBattle { get; set; }
    public int MonsterType { get; set; }
    public int MonsterGradeIcon { get; set; }
    public int StatId { get; set; }
    public int FightType { get; set; }
    public int MonsterSkillLinkId { get; set; }
    public int Material { get; set; }
    public int WeaponType { get; set; }
    public int AttackMotionSpeed { get; set; }
    public int Ability { get; set; }
    public int StandardWalkSpeed { get; set; }
    public int StandardRunSpeed { get; set; }
    public int WalkSpeed { get; set; }
    public int RunSpeed { get; set; }
    public decimal AttackRange { get; set; }
    public decimal HidesenseRange { get; set; }
    public int Hp { get; set; }
    public int Mp { get; set; }
    public int AttackPoint { get; set; }
    public int MagicPoint { get; set; }
    public int Defence { get; set; }
    public int MagicDefence { get; set; }
    public int AttackSpeed { get; set; }
    public int MagicSpeed { get; set; }
    public int Accuracy { get; set; }
    public int Avoid { get; set; }
    public int MagicAccuracy { get; set; }
    public int MagicAvoid { get; set; }
    public int TamingId { get; set; }
    public int CreatureTamingCode { get; set; }
    public decimal TamingPercentage { get; set; }
    public decimal TamingExpMod { get; set; }
    public int Exp { get; set; }
    public int Jp { get; set; }
    public int GoldDropPercentage { get; set; }
    public int GoldMin { get; set; }
    public int GoldMax { get; set; }
    public int ChaosDropPercentage { get; set; }
    public int ChaosMin { get; set; }
    public int ChaosMax { get; set; }
    public int Exp2 { get; set; }
    public int Jp2 { get; set; }
    public int GoldMin2 { get; set; }
    public int GoldMax2 { get; set; }
    public int ChaosMin2 { get; set; }
    public int ChaosMax2 { get; set; }
    public int DropTableLinkId { get; set; }
    public int TextureGroup { get; set; }
    public int LocalFlag { get; set; }
    public string ScriptOnDead { get; set; }
    public int RespawnGroup { get; set; }
}
