namespace Navislamia.Game.Services.Stats;

public enum StatTarget
{
    None = 0,
    Strength,
    Vitality,
    Dexterity,
    Agility,
    Intelligence,
    Wisdom,
    Luck,
    AttackPointRight,
    AttackPointLeft,
    MagicPoint,
    Defence,
    MagicDefence,
    BlockDefence,
    BlockChance,
    AccuracyRight,
    AccuracyLeft,
    MagicAccuracy,
    Avoid,
    MagicAvoid,
    Critical,
    CriticalPower,
    AttackSpeed,
    CastingSpeed,
    CoolTimeSpeed,
    MoveSpeed,
    AttackRange,
    MaxWeight,
    ItemChance,
    HpRegenPoint,
    HpRegenPercentage,
    MpRegenPoint,
    MpRegenPercentage,
    MaxHp,
    MaxMp,
    MaxStamina,
    MaxChaos
}
