START TRANSACTION;

CREATE TABLE "CharacterStates" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CharacterId" bigint NOT NULL,
    "SummonCardId" bigint NOT NULL,
    "StateId" integer NOT NULL,
    "SkillId" integer NOT NULL,
    "StateLevel" integer NOT NULL,
    "RemainingTicks" bigint NOT NULL,
    "Infinite" boolean NOT NULL,
    "SavedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CharacterStates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterStates_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CharacterStates_CharacterId_SummonCardId" ON "CharacterStates" ("CharacterId", "SummonCardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261002115217_Version0012_CharacterStates', '8.0.0');

COMMIT;

