namespace Navislamia.Game.Network.Packets.Enums;

public enum GamePackets : ushort
{
    TM_SC_RESULT = 0,

    TM_CS_LOGIN = 1,
    TM_TIMESYNC = 2,
    TM_SC_ENTER = 3,
    TM_SC_LOGIN_RESULT = 4,
    TM_CS_MOVE_REQUEST = 5,
    TM_CS_REGION_UPDATE = 7,
    TM_SC_MOVE = 8,
    TM_SC_LEAVE = 9,
    TM_SC_SET_TIME = 10,
    TM_SC_WARP = 12,
    TM_CS_QUERY = 13,
    TM_CS_CHAT_REQUEST = 20,
    TM_SC_CHAT_LOCAL = 21,
    TM_SC_CHAT = 22,
    TM_SC_CHAT_RESULT = 24,
    TM_CS_ATTACK_REQUEST = 100,
    TM_SC_ATTACK_EVENT = 101,
    TM_CS_CANCEL_ACTION = 150,
    TM_CS_PUTON_ITEM = 200,
    TM_CS_PUTOFF_ITEM = 201,
    TM_SC_WEAR_INFO = 202,
    TM_SC_ITEM_WEAR_INFO = 287,
    TM_SC_INVENTORY = 207,
    TM_CS_ERASE_ITEM = 208,
    TM_SC_ERASE_ITEM = 209,
    TM_CS_TAKE_ITEM = 204,
    TM_SC_TAKE_ITEM_RESULT = 210,
    TM_SC_BELT_SLOT_INFO = 216,
    TM_SC_ITEM_COOL_TIME = 217,
    TM_CS_CHANGE_ITEM_POSITION = 218,
    TM_CS_ARRANGE_ITEM = 219,
    TM_SC_HAIR_INFO = 220,
    TM_SC_HIDE_EQUIP_INFO = 222,
    TM_SC_SKIN_INFO = 224,
    TM_EQUIP_SUMMON = 303,
    TM_CS_SKILL = 400,
    TM_SC_SKILL = 401,
    TM_CS_LEARN_SKILL = 402,
    TM_SC_SKILL_LIST = 403,
    TM_SC_ADDED_SKILL_LIST = 404,
    TM_SC_AURA = 407,
    TM_CS_JOB_LEVEL_UP = 410,

    TM_SC_STATUS_CHANGE = 500,
    TM_SC_STATE = 505,
    TM_CS_UPDATE = 503,
    TM_SC_PROPERTY = 507,
    TM_CS_SET_PROPERTY = 508,
    TM_CS_TARGETING = 511,
    TM_CS_MONSTER_RECOGNIZE = 517,
    TM_CS_CHANGE_LOCATION = 900,
    TM_SC_STAT_INFO = 1000,
    TM_SC_GOLD_UPDATE = 1001,
    TM_SC_LEVEL_UPDATE = 1002,
    TM_SC_EXP_UPDATE = 1003,

    TM_CS_GAME_TIME = 1100,
    TM_SC_GAME_TIME = 1101,
    TM_SC_DIALOG = 3000,
    TM_CS_DIALOG = 3001,
    TM_CS_CONTACT = 3002,

    TM_CS_RETURN_LOBBY = 23,
    TM_CS_REQUEST_RETURN_LOBBY = 25,
    TM_CS_REQUEST_LOGOUT = 26,
    TM_CS_LOGOUT = 27,
    TM_SC_DISCONNECT_DESC = 28,

    TM_CS_VERSION = 50,

    TM_CS_CHARACTER_LIST = 2001,

    TM_CS_CREATE_CHARACTER = 2002,

    TM_CS_DELETE_CHARACTER = 2003,

    TM_CS_ACCOUNT_WITH_AUTH = 2005,

    TM_CS_CHECK_CHARACTER_NAME = 2006,

    TM_CS_REPORT = 8000,

    TM_NONE = 9999
}
