"""Reconstruct missing trigger branches from imported profiles; never manufacture skill IDs.

Reuse the official branch of a monster with the identical skill link. For a new link,
pair trigger slots with zero-probability skills first (then ordinary skills), retaining
resource order and the skill's harmful/self target. Empty links explicitly do nothing.
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build(resources, links, triggers, skills, covered):
    representatives = {}
    for row in sorted(resources, key=lambda r: int(r['id'])):
        if int(row['id']) in covered:
            representatives.setdefault(row['monster_skill_link_id'], int(row['id']))
    profiles = {}
    for row in sorted(resources, key=lambda r: int(r['id'])):
        code = int(row['id'])
        link = row['monster_skill_link_id']
        if code in covered or not triggers.get(link):
            continue
        if link in representatives:
            profiles[code] = {'alias': representatives[link]}
            continue
        entries = links.get(link, [])
        indices = [i for i, entry in enumerate(entries) if entry['Probability'] <= 0]
        indices.extend(i for i in range(len(entries)) if i not in indices)
        actions = []
        for i, _ in enumerate(triggers[link]):
            if i >= len(indices):
                actions.append(None)
                continue
            index = indices[i]
            skill = skills.get(str(entries[index]['SkillId']))
            actions.append({'index': index, 'self': skill['is_harmful'] != '1'} if skill else None)
        profiles[code] = {'actions': actions}
    return profiles


def main():
    def rows(name):
        with (ROOT / 'data/epic7' / f'{name}.csv').open(encoding='utf-8-sig') as stream:
            return list(csv.DictReader(stream))
    source = (ROOT / 'Game/Scripting/Scripts/monster_triggers.lua').read_text(encoding='utf-8')
    covered = set(map(int, re.findall(r'monster_id\s*==\s*(\d+)', source)))
    data = json.loads((ROOT / 'DevConsole/monster-skills.73.json').read_text(encoding='utf-8-sig'))['MonsterSkillCatalog']
    profiles = build(rows('MonsterResource'), data['Links'], data['Triggers'],
                     {row['id']: row for row in rows('SkillResource')}, covered)
    lines = ['-- Generated by tools/export_monster_trigger_profiles.py; inferred from imported resources.',
             'navis_reconstructed_triggers = {']
    for code, profile in profiles.items():
        if 'alias' in profile:
            value = '{alias = %d}' % profile['alias']
        else:
            actions = ', '.join('{index = %d, self = %s}' % (a['index'], str(a['self']).lower())
                                if a else 'false' for a in profile['actions'])
            value = '{actions = {' + actions + '}}'
        lines.append('    [%d] = %s,' % (code, value))
    lines.append('}\n')
    (ROOT / 'Game/Scripting/Scripts/monster_trigger_profiles.lua').write_text('\n'.join(lines), encoding='utf-8')
    print('Missing profiles:', len(profiles), 'official aliases:', sum('alias' in p for p in profiles.values()),
          'empty action profiles:', sum('actions' in p and not any(p['actions']) for p in profiles.values()))


if __name__ == '__main__':
    main()
