"""Generate the embedded Arcadia data migration from Epic 7 ItemResource.limit_*.

Run from any directory: python tools/generate_item_wear_restrictions.py
Only race/class whitelist masks and job_depth are updated, only for IDs in the CSV.
The SQL travels inside Modules.Game so deployment needs neither the CSV nor Python.
"""
import csv
import hashlib
from collections import defaultdict

from import_epic7 import DATA, ROOT, ITEM_RACE_LIMITS, ITEM_JOB_LIMITS, whitelist_mask

OUTPUT = ROOT / "Game" / "DataAccess" / "Migrations" / "Arcadia" / "ItemWearRestrictions.sql"


def generate(source):
    groups = defaultdict(list)
    seen = set()
    with source.open(encoding="utf-8", newline="") as stream:
        for row in csv.DictReader(stream):
            code = int(row["id"])
            if code <= 0 or code in seen:
                raise ValueError(f"Invalid or duplicate item ID: {code}")
            seen.add(code)
            depth = int(row["job_depth"])
            if depth < 0 or depth > 15:
                raise ValueError(f"Item {code}: invalid depth mask {depth}")
            masks = (whitelist_mask(row, ITEM_RACE_LIMITS), whitelist_mask(row, ITEM_JOB_LIMITS), depth)
            groups[masks].append(code)
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    lines = ["-- Generated by tools/generate_item_wear_restrictions.py; do not edit by hand.",
             f"-- Source: data/epic7/{source.name}; SHA256 {digest}",
             f"-- {len(seen)} item IDs, {len(groups)} whitelist/depth combinations.",
             "-- Repository race bits: Deva=1, Asura=2, Gaia=4. Class bits: 1024/2048/4096/8192.",
             "-- Unknown IDs and all other item columns are left untouched.", ""]
    for (race, job, depth), ids in sorted(groups.items()):
        lines.extend([f'UPDATE "ItemResources" SET "RaceRestriction" = {race}, "JobRestriction" = {job}, "JobDepth" = {depth}',
                      'WHERE "Id" IN ('])
        ids.sort()
        for index in range(0, len(ids), 12):
            chunk = ids[index:index + 12]
            lines.append("    " + ", ".join(map(str, chunk)) + ("," if index + 12 < len(ids) else ""))
        lines.extend([");", ""])
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(generate(DATA / "ItemResource.csv"), encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.name}")
